/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FmrVista;

import Clases.Pila;
import Clases.Notas;

/**
 *
 * @author Usuario
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txa_resultado = new javax.swing.JTextArea();
        pn_principal = new javax.swing.JPanel();
        lb_titulo = new javax.swing.JLabel();
        lb_autor = new javax.swing.JLabel();
        lb_tamañoPila = new javax.swing.JLabel();
        txt_tamañoPila = new javax.swing.JTextField();
        btn_crearPila = new javax.swing.JButton();
        btn_apilar = new javax.swing.JButton();
        btn_desapilar = new javax.swing.JButton();
        btn_lleno = new javax.swing.JButton();
        btn_vacio = new javax.swing.JButton();
        btn_cima = new javax.swing.JButton();
        btn_numeroElementos = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txa_imprimir = new javax.swing.JTextArea();
        btn_reiniciar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_numCedula = new javax.swing.JTextField();
        txt_codMateria = new javax.swing.JTextField();
        txt_notaSupletorio = new javax.swing.JTextField();
        txt_nota2 = new javax.swing.JTextField();
        txt_nota1 = new javax.swing.JTextField();
        btn_reporte = new javax.swing.JButton();

        txa_resultado.setColumns(20);
        txa_resultado.setRows(5);
        jScrollPane1.setViewportView(txa_resultado);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_titulo.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        lb_titulo.setText("ESTRUCTURA DE DATOS PILA");

        lb_autor.setText("Elaborado por: Ramírez Henry");

        lb_tamañoPila.setText("Tamaño para la Pila");

        txt_tamañoPila.setText("5");
        txt_tamañoPila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tamañoPilaActionPerformed(evt);
            }
        });

        btn_crearPila.setText("Crear Pila");
        btn_crearPila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearPilaActionPerformed(evt);
            }
        });

        btn_apilar.setText("Apilar");
        btn_apilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_apilarActionPerformed(evt);
            }
        });

        btn_desapilar.setText("Desapilar");
        btn_desapilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_desapilarActionPerformed(evt);
            }
        });

        btn_lleno.setText("Lleno");
        btn_lleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_llenoActionPerformed(evt);
            }
        });

        btn_vacio.setText("Vacío");
        btn_vacio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vacioActionPerformed(evt);
            }
        });

        btn_cima.setText("Cima");
        btn_cima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cimaActionPerformed(evt);
            }
        });

        btn_numeroElementos.setText("Número de elementos");
        btn_numeroElementos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_numeroElementosActionPerformed(evt);
            }
        });

        txa_imprimir.setColumns(20);
        txa_imprimir.setRows(5);
        jScrollPane2.setViewportView(txa_imprimir);

        btn_reiniciar.setText("Reiniciar");
        btn_reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reiniciarActionPerformed(evt);
            }
        });

        jLabel1.setText("Número de cédula");

        jLabel2.setText("Código de materia");

        jLabel3.setText("NOTA 1");

        jLabel4.setText("NOTA 2");

        jLabel5.setText("NOTA SUPLETORIO");

        btn_reporte.setText("REPORTE");
        btn_reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_principalLayout = new javax.swing.GroupLayout(pn_principal);
        pn_principal.setLayout(pn_principalLayout);
        pn_principalLayout.setHorizontalGroup(
            pn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_principalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lb_titulo)
                .addGap(103, 103, 103))
            .addGroup(pn_principalLayout.createSequentialGroup()
                .addGroup(pn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_principalLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(pn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_autor)
                            .addGroup(pn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(pn_principalLayout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addGroup(pn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pn_principalLayout.createSequentialGroup()
                                            .addGroup(pn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(pn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel1)
                                                    .addGroup(pn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel4)))
                                                .addComponent(lb_tamañoPila))
                                            .addGap(62, 62, 62)
                                            .addGroup(pn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(pn_principalLayout.createSequentialGroup()
                                                    .addComponent(txt_tamañoPila, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btn_crearPila, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(txt_codMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txt_numCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txt_nota1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txt_nota2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txt_notaSupletorio, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(pn_principalLayout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(97, 97, 97))))
                                .addGroup(pn_principalLayout.createSequentialGroup()
                                    .addGroup(pn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pn_principalLayout.createSequentialGroup()
                                            .addComponent(btn_cima, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btn_reiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(pn_principalLayout.createSequentialGroup()
                                            .addComponent(btn_vacio, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btn_lleno, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(pn_principalLayout.createSequentialGroup()
                                            .addComponent(btn_apilar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btn_desapilar))
                                        .addGroup(pn_principalLayout.createSequentialGroup()
                                            .addGap(16, 16, 16)
                                            .addComponent(btn_numeroElementos)))
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pn_principalLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(btn_reporte)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        pn_principalLayout.setVerticalGroup(
            pn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_principalLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lb_titulo)
                .addGroup(pn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_principalLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lb_autor)
                        .addGap(53, 53, 53)
                        .addGroup(pn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_tamañoPila)
                            .addComponent(txt_tamañoPila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_crearPila))
                        .addGap(25, 25, 25)
                        .addGroup(pn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_numCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_codMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_nota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_nota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_notaSupletorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(btn_reporte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_apilar)
                            .addComponent(btn_desapilar))
                        .addGap(10, 10, 10)
                        .addGroup(pn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_vacio)
                            .addComponent(btn_lleno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_cima)
                            .addComponent(btn_reiniciar))
                        .addGap(18, 18, 18)
                        .addComponent(btn_numeroElementos)
                        .addContainerGap(14, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_principalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_tamañoPilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tamañoPilaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tamañoPilaActionPerformed

    private void btn_cimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cimaActionPerformed
        Object aux = this.pila.cima();
        Notas not;
        if (aux != null) {
            not = (Notas) aux;
            this.txa_imprimir.setText("cima: " + not.getCédula() + "\n" + not.getNota1() + "\n" + not.getNota2() + "\n" + not.getNotaSupletorio());
        } else {
            this.texto += "\nla pila esta vacía";
            this.txa_imprimir.setText(texto);
        }
    }//GEN-LAST:event_btn_cimaActionPerformed

    private void btn_numeroElementosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_numeroElementosActionPerformed
        if (this.pila != null) {
            this.texto += "\n" + this.pila.getNúmeroElementos();            
            this.txa_imprimir.setText(texto);
        } else {
            this.texto += "\nla pila aun no esta creada";
            this.txa_imprimir.setText(texto);
        }
    }//GEN-LAST:event_btn_numeroElementosActionPerformed

    private void btn_crearPilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearPilaActionPerformed
        int tamaño;
        if (this.validarNumero(this.txt_tamañoPila.getText())) {
            tamaño = Integer.parseInt(this.txt_tamañoPila.getText());
            if (tamaño > 0) {
                this.pila = new Pila(tamaño);
                this.texto += "\npila creada correctamente";
                this.txa_imprimir.setText(texto);
            } else {
                this.texto += "\nla pila no pudo ser creada";
                this.txa_imprimir.setText(texto);
            }
        }
    }//GEN-LAST:event_btn_crearPilaActionPerformed

    public boolean validarNumero(String dato) {
        try {
            Integer.parseInt(dato);
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    private void btn_apilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_apilarActionPerformed

        if (this.pila == null) {
            this.texto += "\n" + "la pila no ha sido creada";
            this.txa_imprimir.setText(texto);
        } else if (!this.pila.lleno()) {
            String cedula = this.txt_numCedula.getText();
            String codMateria = this.txt_codMateria.getText();
            double n1 = Double.parseDouble(this.txt_nota1.getText());
            double n2 = Double.parseDouble(this.txt_nota2.getText());
            double nSupletorio = Double.parseDouble(this.txt_notaSupletorio.getText());

            Notas notasDatos = new Notas(cedula, codMateria, n1, n2, nSupletorio);
            this.texto += "\n" + this.pila.apilar(notasDatos);
            this.txa_imprimir.setText(texto);
        } else {
            this.texto += "\nno se pudo apilar porque la pila esta llena";
            this.txa_imprimir.setText(texto);
        }
    }//GEN-LAST:event_btn_apilarActionPerformed

    private void btn_desapilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_desapilarActionPerformed
        if (this.pila != null) {
            if (!this.pila.vacio()) {
                this.texto += "\n" + this.pila.desapilar();
                this.txa_imprimir.setText(texto);
            } else {
                this.texto += "\n" + "No se puede desapilar la pila porque esta vacia";
                this.txa_imprimir.setText(texto);
            }
        } else {
            this.texto += "\n" + "No se pudo desapilar por que aun no se ha creado la pila";
            this.txa_imprimir.setText(texto);
        }

    }//GEN-LAST:event_btn_desapilarActionPerformed

    private void btn_vacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vacioActionPerformed
        if (this.pila != null) {
            if (this.pila.vacio()) {
                this.texto += "\npila vacía";
            } else {
                this.texto += "\npila no está vacía";
            }
            this.txa_imprimir.setText(texto);
        }
    }//GEN-LAST:event_btn_vacioActionPerformed

    private void btn_llenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_llenoActionPerformed
        if (this.pila != null) {
            if (this.pila.lleno()) {
                this.texto += "\npila llena";
            } else {
                this.texto += "\npila no está llena";
            }
            this.txa_imprimir.setText(texto);
        }
    }//GEN-LAST:event_btn_llenoActionPerformed

    private void btn_reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reiniciarActionPerformed
        this.txa_imprimir.setText("");
        this.texto = "";
        this.txt_codMateria.setText("");
        this.txt_notaSupletorio.setText("");
        this.txt_nota1.setText("");
        this.txt_nota2.setText("");
        this.pila = null;
    }//GEN-LAST:event_btn_reiniciarActionPerformed

    private void btn_reporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reporteActionPerformed
        Object auxObject;
        Notas auxNotas;
        Pila auxPila = new Pila(this.pila.getTamaño());
        String informacion = "";

        if (this.pila != null) {
            while (this.pila.vacio() == false){                            
                auxObject = this.pila.cima();
                auxNotas = (Notas) auxObject;
                auxPila.apilar(auxNotas);
                informacion += "\n" + "Cédula: " + auxNotas.getCédula() +
                        " Código materia: " + auxNotas.getCodigoMateria() +
                        " Nota 1: " + auxNotas.getNota1() + 
                        " Nota 2: " + auxNotas.getNota2() +
                        " Nota Supletorio: " + auxNotas.getNotaSupletorio();
                this.pila.desapilar();
            }
            while (auxPila.vacio() == false){
                this.pila.apilar(auxPila);
                auxPila.desapilar();
                
            }
            this.txa_imprimir.setText(informacion);
        } else {
            this.texto += "\nla pila aun no ha sido creada";
            this.txa_imprimir.setText(texto);
        }
    }//GEN-LAST:event_btn_reporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    Pila pila;
    String texto = "";

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_apilar;
    private javax.swing.JButton btn_cima;
    private javax.swing.JButton btn_crearPila;
    private javax.swing.JButton btn_desapilar;
    private javax.swing.JButton btn_lleno;
    private javax.swing.JButton btn_numeroElementos;
    private javax.swing.JButton btn_reiniciar;
    private javax.swing.JButton btn_reporte;
    private javax.swing.JButton btn_vacio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_autor;
    private javax.swing.JLabel lb_tamañoPila;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.JPanel pn_principal;
    private javax.swing.JTextArea txa_imprimir;
    private javax.swing.JTextArea txa_resultado;
    private javax.swing.JTextField txt_codMateria;
    private javax.swing.JTextField txt_nota1;
    private javax.swing.JTextField txt_nota2;
    private javax.swing.JTextField txt_notaSupletorio;
    private javax.swing.JTextField txt_numCedula;
    private javax.swing.JTextField txt_tamañoPila;
    // End of variables declaration//GEN-END:variables
}
