/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.ed.relacionpropiedades;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_conjunto = new javax.swing.JTextField();
        btn_conjunto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_A = new javax.swing.JTable();
        btn_relacion = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn_reflexiva = new javax.swing.JButton();
        btn_simetrica = new javax.swing.JButton();
        btn_irreflexiva = new javax.swing.JButton();
        btn_asimetrica = new javax.swing.JButton();
        btn_antisimetrica = new javax.swing.JButton();
        btn_transitiva = new javax.swing.JButton();
        btn_equivalente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txa_imprimir = new javax.swing.JTextArea();
        btn_reiniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("PROPIEDADES DE LAS RELACIONES");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Autor: Ramírez Montalvo Luis Henry");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("CONJUNTO");

        jLabel4.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("RELACIÓN");

        jLabel5.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("PROPIEDADES");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("A = {");

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText(" } ");

        txt_conjunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_conjuntoActionPerformed(evt);
            }
        });

        btn_conjunto.setBackground(new java.awt.Color(255, 255, 255));
        btn_conjunto.setForeground(new java.awt.Color(0, 0, 0));
        btn_conjunto.setText("Enviar");
        btn_conjunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_conjuntoActionPerformed(evt);
            }
        });

        tb_A.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_A);

        btn_relacion.setBackground(new java.awt.Color(255, 255, 255));
        btn_relacion.setForeground(new java.awt.Color(0, 0, 0));
        btn_relacion.setText("Enviar");
        btn_relacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_relacionActionPerformed(evt);
            }
        });

        btn_reflexiva.setBackground(new java.awt.Color(255, 255, 255));
        btn_reflexiva.setForeground(new java.awt.Color(0, 0, 0));
        btn_reflexiva.setText("Reflexiva");
        btn_reflexiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reflexivaActionPerformed(evt);
            }
        });

        btn_simetrica.setBackground(new java.awt.Color(255, 255, 255));
        btn_simetrica.setForeground(new java.awt.Color(0, 0, 0));
        btn_simetrica.setText("Simétrica");
        btn_simetrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simetricaActionPerformed(evt);
            }
        });

        btn_irreflexiva.setBackground(new java.awt.Color(255, 255, 255));
        btn_irreflexiva.setForeground(new java.awt.Color(0, 0, 0));
        btn_irreflexiva.setText("Irreflexiva");
        btn_irreflexiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_irreflexivaActionPerformed(evt);
            }
        });

        btn_asimetrica.setBackground(new java.awt.Color(255, 255, 255));
        btn_asimetrica.setForeground(new java.awt.Color(0, 0, 0));
        btn_asimetrica.setText("Asimétrica");
        btn_asimetrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_asimetricaActionPerformed(evt);
            }
        });

        btn_antisimetrica.setBackground(new java.awt.Color(255, 255, 255));
        btn_antisimetrica.setForeground(new java.awt.Color(0, 0, 0));
        btn_antisimetrica.setText("Antisimétrica");
        btn_antisimetrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_antisimetricaActionPerformed(evt);
            }
        });

        btn_transitiva.setBackground(new java.awt.Color(255, 255, 255));
        btn_transitiva.setForeground(new java.awt.Color(0, 0, 0));
        btn_transitiva.setText("Transitiva");
        btn_transitiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transitivaActionPerformed(evt);
            }
        });

        btn_equivalente.setBackground(new java.awt.Color(255, 255, 255));
        btn_equivalente.setForeground(new java.awt.Color(0, 0, 0));
        btn_equivalente.setText("Equivalente");
        btn_equivalente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_equivalenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_simetrica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_irreflexiva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_asimetrica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_antisimetrica, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_transitiva, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_reflexiva, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_equivalente, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_reflexiva)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_irreflexiva)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_simetrica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_asimetrica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_antisimetrica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_transitiva)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_equivalente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txa_imprimir.setColumns(20);
        txa_imprimir.setRows(5);
        jScrollPane2.setViewportView(txa_imprimir);

        btn_reiniciar.setBackground(new java.awt.Color(255, 255, 255));
        btn_reiniciar.setForeground(new java.awt.Color(0, 0, 0));
        btn_reiniciar.setText("Reiniciar");
        btn_reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reiniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_conjunto))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(42, 42, 42)
                                        .addComponent(btn_conjunto))
                                    .addComponent(btn_relacion)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(btn_reiniciar))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(txt_conjunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_conjunto))
                                .addGap(213, 213, 213)
                                .addComponent(btn_relacion))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2))
                            .addComponent(btn_reiniciar, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simetricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simetricaActionPerformed
        if (this.relacion == null) {
            JOptionPane.showMessageDialog(null, "Complete el conjunto y la relación por favor");
        } else {
            if (this.relacion.P_Simetrica()) {
                this.text = this.text + " SI cumple con la propiedad SIMÉTRICA \n";
            } else {
                this.text = this.text + " NO cumple con la propiedad SIMÉTRICA \n";
            }
            this.txa_imprimir.setText(this.text);
        }
    }//GEN-LAST:event_btn_simetricaActionPerformed

    private void btn_asimetricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_asimetricaActionPerformed
        if (this.relacion == null) {
            JOptionPane.showMessageDialog(null, "Complete el conjunto y la relación por favor");
        } else {
            if (this.relacion.P_Asimetrica()) {
                this.text = this.text + " SI cumple con la propiedad ASIMÉTRICA \n";
            } else {
                this.text = this.text + " NO cumple con la propiedad ASIMÉTRICA \n";
            }
            this.txa_imprimir.setText(this.text);
        }
    }//GEN-LAST:event_btn_asimetricaActionPerformed

    private void btn_antisimetricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_antisimetricaActionPerformed
        if (this.relacion == null) {
            JOptionPane.showMessageDialog(null, "Complete el conjunto y la relación por favor");
        } else {
            if (this.relacion.P_Antisimetrica()) {
                this.text = this.text + " SI cumple con la propiedad ANTISIMÉTRICA \n";
            } else {
                this.text = this.text + " NO cumple con la propiedad ANTISIMÉTRICA \n";
            }
            this.txa_imprimir.setText(this.text);
        }
    }//GEN-LAST:event_btn_antisimetricaActionPerformed

    private void btn_transitivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transitivaActionPerformed
        if (this.relacion == null) {
            JOptionPane.showMessageDialog(null, "Complete el conjunto y la relación por favor");
        } else {
            if (this.relacion.P_Transitiva()) {
                this.text = this.text + " SI cumple con la propiedad TRANSITIVA \n";
            } else {
                this.text = this.text + " NO cumple con la propiedad TRANSITIVA \n";
            }
            this.txa_imprimir.setText(this.text);
        }
    }//GEN-LAST:event_btn_transitivaActionPerformed

    private void btn_equivalenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_equivalenteActionPerformed
        if (this.relacion == null) {
            JOptionPane.showMessageDialog(null, "Complete el conjunto y la relación por favor");
        } else {
            if (this.relacion.P_Equivalencia()) {
                this.text = this.text + " SI cumple con la propiedad de EQUIVALENCIA \n";
            } else {
                this.text = this.text + " NO cumple con la propiedad de EQUIVALENCIA \n";
            }
            this.txa_imprimir.setText(this.text);
        }
    }//GEN-LAST:event_btn_equivalenteActionPerformed

    private void btn_conjuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_conjuntoActionPerformed

        String[] conjunto = this.txt_conjunto.getText().replaceAll("\\s", "").split(",");
        if (this.VALIDAR_CONJUNTO(conjunto)) {
            this.aux_tb = new DefaultTableModel();
            this.aux_tb.setColumnCount(conjunto.length);
            this.aux_tb.setRowCount(conjunto.length);
            this.tb_A.setModel(aux_tb);
        } else {
            this.txt_conjunto.setText("");
            JOptionPane.showMessageDialog(null, "El conjunto solo acepta números");
        }
    }//GEN-LAST:event_btn_conjuntoActionPerformed

    private void txt_conjuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_conjuntoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_conjuntoActionPerformed

    private void btn_relacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_relacionActionPerformed
        if (this.txt_conjunto.getText().replaceAll("\\s", "").equals("")) {
            JOptionPane.showMessageDialog(null, "Escriba un conjunto de números por favor");
        } else {
            String[] conjunto = this.txt_conjunto.getText().replaceAll("\\s", "").split(",");
            int tamaño = conjunto.length;
            int[][] matriz = new int[tamaño][tamaño];
            for (int i = 0; i < tamaño; i++) {
                for (int j = 0; j < tamaño; j++) {
                    matriz[i][j] = Integer.parseInt(this.tb_A.getValueAt(i, j) + "");
                }
            }
            if (this.relacion == null) {
                this.relacion = new Relacion(matriz);
            } else {
                this.relacion.setMatriz(matriz);
            }
        }
    }//GEN-LAST:event_btn_relacionActionPerformed

    private void btn_reflexivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reflexivaActionPerformed
        if (this.relacion == null) {
            JOptionPane.showMessageDialog(null, "Complete el conjunto y la relación por favor");
        } else {
            if (this.relacion.P_Reflexiva() == true) {
                this.text = this.text + " SI cumple con la propiedad REFLEXIVA \n";
            } else {
                this.text = this.text + " NO cumple con la propiedad REFLEXIVA \n";
            }
            this.txa_imprimir.setText(this.text);
        }
    }//GEN-LAST:event_btn_reflexivaActionPerformed

    private void btn_irreflexivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_irreflexivaActionPerformed
        if (this.relacion == null) {
            JOptionPane.showMessageDialog(null, "Complete el conjunto y la relación por favor");
        } else {
            if (this.relacion.P_Irreflexiva()) {
                this.text = this.text + " SI cumple con la propiedad IRREFLEXIVA \n";
            } else {
                this.text = this.text + " NO cumple con la propiedad IRREFLEXIVA \n";
            }
            this.txa_imprimir.setText(this.text);
        }
    }//GEN-LAST:event_btn_irreflexivaActionPerformed

    private void btn_reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reiniciarActionPerformed
        this.relacion = null;
        this.text = "";
        this.txa_imprimir.setText("");
        this.txt_conjunto.setText("");
    }//GEN-LAST:event_btn_reiniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    public boolean VALIDAR_CONJUNTO(String[] conjunto) {
        try {
            for (int x = 0; x < conjunto.length; x++) {
                int num = Integer.parseInt(conjunto[x]);
            }
            return true;
        } catch (Exception e) {
            return false;
        }
    }
    // Variables declaration - do not modify 
    String text = "";
    Relacion relacion;
    DefaultTableModel aux_tb;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_antisimetrica;
    private javax.swing.JButton btn_asimetrica;
    private javax.swing.JButton btn_conjunto;
    private javax.swing.JButton btn_equivalente;
    private javax.swing.JButton btn_irreflexiva;
    private javax.swing.JButton btn_reflexiva;
    private javax.swing.JButton btn_reiniciar;
    private javax.swing.JButton btn_relacion;
    private javax.swing.JButton btn_simetrica;
    private javax.swing.JButton btn_transitiva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tb_A;
    private javax.swing.JTextArea txa_imprimir;
    private javax.swing.JTextField txt_conjunto;
    // End of variables declaration//GEN-END:variables
}
