/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FmrVista;

import Clases.Cola;
import Clases.Pila;
import Clases.Productos;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class FmrPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Windows
     */
    public FmrPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_tamaño = new javax.swing.JTextField();
        btn_crearCola = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JTextField();
        txt_codigo = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_precio = new javax.swing.JTextField();
        btn_vacio = new javax.swing.JButton();
        btn_lleno = new javax.swing.JButton();
        btn_ingresar = new javax.swing.JButton();
        btn_retirar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txa_imprimir = new javax.swing.JTextArea();
        btn_elementos = new javax.swing.JButton();
        btn_primerElemento = new javax.swing.JButton();
        btn_reporte = new javax.swing.JButton();
        btn_comprar = new javax.swing.JButton();
        btn_vender = new javax.swing.JButton();
        txt_minimo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_codigoCV = new javax.swing.JTextField();
        txt_cantidadCV = new javax.swing.JTextField();
        btn_examen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        jLabel1.setText("APLICACIÓN DE COLAS");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Elaborado por: Ramírez Henry");

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel3.setText("Tamaño Cola");

        btn_crearCola.setFont(new java.awt.Font("Arial Narrow", 0, 15)); // NOI18N
        btn_crearCola.setText("Crear Cola");
        btn_crearCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearColaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel4.setText("Código");

        jLabel5.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel5.setText("Nombre");

        jLabel6.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel6.setText("Cantidad");

        jLabel7.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel7.setText("Mínimo");

        jLabel8.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel8.setText("Precio");

        btn_vacio.setFont(new java.awt.Font("Arial Narrow", 0, 15)); // NOI18N
        btn_vacio.setText("Vacio");
        btn_vacio.setActionCommand("");
        btn_vacio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vacioActionPerformed(evt);
            }
        });

        btn_lleno.setFont(new java.awt.Font("Arial Narrow", 0, 15)); // NOI18N
        btn_lleno.setText("Lleno");
        btn_lleno.setActionCommand("");
        btn_lleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_llenoActionPerformed(evt);
            }
        });

        btn_ingresar.setFont(new java.awt.Font("Arial Narrow", 0, 15)); // NOI18N
        btn_ingresar.setText("Ingresar");
        btn_ingresar.setActionCommand("");
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });

        btn_retirar.setFont(new java.awt.Font("Arial Narrow", 0, 15)); // NOI18N
        btn_retirar.setText("Retirar");
        btn_retirar.setActionCommand("");
        btn_retirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_retirarActionPerformed(evt);
            }
        });

        txa_imprimir.setColumns(20);
        txa_imprimir.setRows(5);
        jScrollPane1.setViewportView(txa_imprimir);

        btn_elementos.setFont(new java.awt.Font("Arial Narrow", 0, 15)); // NOI18N
        btn_elementos.setText("Elementos");
        btn_elementos.setActionCommand("");
        btn_elementos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_elementosActionPerformed(evt);
            }
        });

        btn_primerElemento.setFont(new java.awt.Font("Arial Narrow", 0, 15)); // NOI18N
        btn_primerElemento.setText("Primer E");
        btn_primerElemento.setActionCommand("");
        btn_primerElemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_primerElementoActionPerformed(evt);
            }
        });

        btn_reporte.setFont(new java.awt.Font("Arial Narrow", 0, 15)); // NOI18N
        btn_reporte.setText("Reporte");
        btn_reporte.setActionCommand("");
        btn_reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reporteActionPerformed(evt);
            }
        });

        btn_comprar.setFont(new java.awt.Font("Arial Narrow", 0, 15)); // NOI18N
        btn_comprar.setText("Comprar");
        btn_comprar.setActionCommand("");
        btn_comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_comprarActionPerformed(evt);
            }
        });

        btn_vender.setFont(new java.awt.Font("Arial Narrow", 0, 15)); // NOI18N
        btn_vender.setText("Vender");
        btn_vender.setActionCommand("");
        btn_vender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_venderActionPerformed(evt);
            }
        });

        jLabel9.setText("COMPRA Y VENTA");

        jLabel10.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel10.setText("Código");

        jLabel11.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel11.setText("Cantidad");

        btn_examen.setFont(new java.awt.Font("Arial Narrow", 0, 15)); // NOI18N
        btn_examen.setText("Exámen");
        btn_examen.setActionCommand("");
        btn_examen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_examenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_cantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                                    .addComponent(txt_nombre)
                                    .addComponent(txt_codigo)
                                    .addComponent(txt_minimo))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(169, 169, 169)
                                        .addComponent(jLabel9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(41, 41, 41)
                                                .addComponent(txt_codigoCV))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addGap(48, 48, 48)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btn_vender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txt_cantidadCV)))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_tamaño, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_crearCola)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel8)
                                .addGap(52, 52, 52)
                                .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(132, 132, 132)
                                .addComponent(btn_comprar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn_lleno, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_reporte, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_retirar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn_vacio, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_elementos, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_primerElemento, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_examen, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_tamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_crearCola))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(txt_codigoCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txt_cantidadCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_vender)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_minimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btn_comprar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_vacio)
                            .addComponent(btn_elementos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_lleno)
                            .addComponent(btn_reporte))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_ingresar)
                            .addComponent(btn_retirar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_primerElemento)
                            .addComponent(btn_examen)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_vacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vacioActionPerformed
        try {
            if (this.cola.vacio()) {
                this.texto = "\n la cola esta vacía";
            } else {
                this.texto = "\n la cola no esta vacía";
            }
            this.txa_imprimir.setText(texto);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "La cola aun no se ha creado");
        }
    }//GEN-LAST:event_btn_vacioActionPerformed

    private void btn_llenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_llenoActionPerformed
        try {
            if (this.cola.lleno()) {
                this.texto = "\n la cola esta llena";
            } else {
                this.texto = "\n la cola no esta llena";
            }
            this.txa_imprimir.setText(texto);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "La cola aun no se ha creado");
        }
    }//GEN-LAST:event_btn_llenoActionPerformed

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed
        try {
            int verificador = this.cola.getNumElementos();
            String codigoProducto = txt_codigo.getText();
            String nombre = txt_nombre.getText();
            int cantidad = Integer.parseInt(txt_cantidad.getText());
            double precio = Double.parseDouble(txt_precio.getText());
            int minimo = Integer.parseInt(txt_minimo.getText());
            this.producto = new Productos(codigoProducto, nombre, cantidad, precio, minimo);
            this.cola.ingresar(this.producto);
            if (verificador != this.cola.getNumElementos()) {
                this.texto = "\n dato ingresado correctamente";
            } else {
                this.texto = "\n dato no ingresado cola llena";
            }
            this.txa_imprimir.setText(texto);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "La cola aun no se ha creado o los datos ingresados fueron incorrectos");
        }
    }//GEN-LAST:event_btn_ingresarActionPerformed

    private void btn_retirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_retirarActionPerformed
        try {
            int verificador = this.cola.getNumElementos();
            this.cola.retirar();
            if (verificador != this.cola.getNumElementos()) {
                this.texto = "\n dato retirado correctamente";
            } else {
                this.texto = "\n no se puede retirar, pila vacia";
            }
            this.txa_imprimir.setText(texto);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "La cola aun no se ha creado");
        }
    }//GEN-LAST:event_btn_retirarActionPerformed

    private void btn_crearColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearColaActionPerformed
        int tamaño;
        try {
            tamaño = Integer.parseInt(txt_tamaño.getText());
            if (tamaño > 0) {
                this.cola = new Cola(tamaño);
                this.texto = "\n pila creada correctamente";
                this.txa_imprimir.setText(texto);
            } else {
                JOptionPane.showMessageDialog(null, "El tamaño de la cola debe ser un número mayor a 0");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "El tamaño de la cola debe ser un número");
        }
    }//GEN-LAST:event_btn_crearColaActionPerformed

    private void btn_elementosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_elementosActionPerformed
        try {
            this.texto = "\n " + this.cola.getNumElementos();
            this.txa_imprimir.setText(texto);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "La cola aun no se ha creado");
        }
    }//GEN-LAST:event_btn_elementosActionPerformed

    private void btn_primerElementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_primerElementoActionPerformed
        try {
            this.producto = (Productos) this.cola.primerElemento();
            this.texto = " PRIMER ELEMENTO ";
            this.texto += "\n---------------------------------------------------\nProducto: " + producto.getCodigoProducto()
                    + "\nNombre: " + producto.getNombre()
                    + "\nCantidad: " + producto.getCantidad()
                    + "\nMinimo: " + producto.getMinimo()
                    + "\nPrecio: " + producto.getPrecio()
                    + "\n---------------------------------------------------\n";
            this.txa_imprimir.setText(texto);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "La cola aun no se ha creado o la cola esta vacía");
        }
    }//GEN-LAST:event_btn_primerElementoActionPerformed

    private void btn_reporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reporteActionPerformed
        try {
            Object objectAux;
            Cola colaAux = new Cola(this.cola.getTamaño());
            Productos productoAux;
            String datos = "Código \t Nombre \t Cantidad \t Mínimo \t Precio";
            while (!this.cola.vacio()) {
                objectAux = this.cola.retirar();
                productoAux = (Productos) objectAux;
                datos += "\n" + productoAux.getCodigoProducto() + "\t"
                        + productoAux.getNombre() + "\t"
                        + productoAux.getCantidad() + "\t"
                        + productoAux.getMinimo() + "\t"
                        + productoAux.getPrecio();
                colaAux.ingresar(productoAux);
            }
            this.cola = colaAux;
            this.txa_imprimir.setText(datos);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "La cola aun no se ha creado o la cola esta vacía");
        }
    }//GEN-LAST:event_btn_reporteActionPerformed

    private void btn_comprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_comprarActionPerformed
        try {
            String dato = "";
            String codigo = this.txt_codigoCV.getText();
            int cantidad = Integer.parseInt(this.txt_cantidadCV.getText());
            Object objectAux;
            Cola colaAux = new Cola(this.cola.getTamaño());
            Productos productoAux;
            while (!this.cola.vacio()) {
                objectAux = this.cola.retirar();
                productoAux = (Productos) objectAux;
                if (productoAux.getCodigoProducto().equals(codigo)) {
                    if (cantidad > 0) {
                        productoAux.setCantidad(productoAux.getCantidad() + cantidad);
                        dato = "Compra realizada correctamente";
                    } else {
                        dato = "Compra no realizada, pedido mal realizado";
                    }
                }
                colaAux.ingresar(productoAux);
            }
            this.cola = colaAux;
            this.txa_imprimir.setText(dato);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "La cola aun no se ha creado o el pedido realizado es incorrecto");
        }
    }//GEN-LAST:event_btn_comprarActionPerformed

    private void btn_venderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_venderActionPerformed
        try {
            String dato = "";
            String codigo = this.txt_codigoCV.getText();
            int cantidad = Integer.parseInt(this.txt_cantidadCV.getText());
            Object objectAux;
            Cola colaAux = new Cola(this.cola.getTamaño());
            Productos productoAux;
            while (!this.cola.vacio()) {
                objectAux = this.cola.retirar();
                productoAux = (Productos) objectAux;
                if (productoAux.getCodigoProducto().equals(codigo)) {
                    if (cantidad <= productoAux.getCantidad() + productoAux.getMinimo()) {
                        if (cantidad <= productoAux.getCantidad()) {
                            productoAux.setCantidad(productoAux.getCantidad() - cantidad);
                        } else {
                            productoAux.setCantidad(0);
                            productoAux.setMinimo(productoAux.getMinimo() - (cantidad - productoAux.getCantidad()));
                        }

                        dato = "Venta realizada correctamente";
                    } else {
                        dato = "Venta no realizada, stock insuficiente";
                    }
                }
                colaAux.ingresar(productoAux);
            }
            this.cola = colaAux;
            this.txa_imprimir.setText(dato);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "La cola aun no se ha creado o la compra realizada es incorrecto");
        }
    }//GEN-LAST:event_btn_venderActionPerformed

    private void btn_examenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_examenActionPerformed
        try {
            Pila pila = new Pila(this.cola.getTamaño());
            Pila pilaAux = new Pila(this.cola.getTamaño());            
            Productos producto1;
            Productos producto2;
            int contador = 0;
            while (!this.cola.vacio()) {
                if (contador == 0) {
                    pila.apilar(this.cola.retirar());
                } else {
                    // la cola tiene el método primer elemento que devuelve un objeto, el primero de la cola
                    producto1 = (Productos) this.cola.primerElemento();
                    producto2 = (Productos) pila.cima();
                    if (producto2.getPrecio() > producto1.getPrecio()) {
                        pila.apilar(this.cola.retirar());
                    } else {
                        //mientras no el precio del elemento sea mayor seguira desapilando y colocandolos en la auxiliar
                        while (producto1.getPrecio() > producto2.getPrecio() && !pila.vacio()) {
                            pilaAux.apilar(pila.Desapilar());
                        }
                        //vuelve a apila los datos ordenados en la pila de la pila Aux
                        pila.apilar(this.cola.retirar());
                        while (!pilaAux.vacio()) {
                            pila.apilar(pilaAux.Desapilar());
                        }
                    }
                }
                contador++;
            }
            while (!pila.vacio()) {
                this.cola.ingresar(pila.Desapilar());
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "La cola aun no se ha creado o tiene 0 elementos");
        }
    }//GEN-LAST:event_btn_examenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FmrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FmrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FmrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FmrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FmrPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do modify                     
    Productos producto;
    Cola cola;
    String texto = "";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_comprar;
    private javax.swing.JButton btn_crearCola;
    private javax.swing.JButton btn_elementos;
    private javax.swing.JButton btn_examen;
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JButton btn_lleno;
    private javax.swing.JButton btn_primerElemento;
    private javax.swing.JButton btn_reporte;
    private javax.swing.JButton btn_retirar;
    private javax.swing.JButton btn_vacio;
    private javax.swing.JButton btn_vender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txa_imprimir;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_cantidadCV;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_codigoCV;
    private javax.swing.JTextField txt_minimo;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_precio;
    private javax.swing.JTextField txt_tamaño;
    // End of variables declaration//GEN-END:variables
}
