/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ed.matrizboleana;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_general = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_fil_A = new javax.swing.JTextField();
        txt_col_A = new javax.swing.JTextField();
        txt_fil_B = new javax.swing.JTextField();
        txt_col_B = new javax.swing.JTextField();
        btn_crear = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_A = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_B = new javax.swing.JTable();
        btn_llenar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_resultante = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lb_producto = new javax.swing.JLabel();
        btn_reiniciar = new javax.swing.JButton();
        btn_junta = new javax.swing.JButton();
        btn_raunion = new javax.swing.JButton();
        btn_producto = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        btn_relacionB = new javax.swing.JButton();
        btn_relacionA = new javax.swing.JButton();
        txt_numRelacion = new javax.swing.JTextField();
        lb_Mr = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btn_producto1 = new javax.swing.JButton();
        btn_propiedades = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pn_general.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel1.setText("MATRICES BOOLEANAS");
        jLabel1.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Autor: Ramírez Montalvo Luis Henry");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Ingresar datos de las matrices");

        jLabel4.setText("Número de filas:");

        jLabel5.setText("Número de columnas:");

        jLabel6.setText("Matriz A");

        jLabel7.setText("Matriz B");

        btn_crear.setText("Crear Matrices");
        btn_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_fil_A, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_col_A, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_col_B, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 264, Short.MAX_VALUE)
                        .addComponent(btn_crear))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_fil_B, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_fil_A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_fil_B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_col_A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_col_B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_crear))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tb_A.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_A);

        jLabel8.setText("MATRIZ A");

        jLabel9.setText("MATRIZ B");

        tb_B.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tb_B);

        btn_llenar.setText("Llenar Matrices");
        btn_llenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_llenarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_llenar)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_llenar)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        tb_resultante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tb_resultante);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel10.setText("MATRIZ RESULTANTE");

        jLabel11.setText("Operaciones");

        jLabel12.setText("Junta");

        jLabel13.setText("Reunión");

        lb_producto.setText("Producto Booleano");

        btn_reiniciar.setText("Reiniciar");
        btn_reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reiniciarActionPerformed(evt);
            }
        });

        btn_junta.setText("Calcular");
        btn_junta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_juntaActionPerformed(evt);
            }
        });

        btn_raunion.setText("Calcular");
        btn_raunion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_raunionActionPerformed(evt);
            }
        });

        btn_producto.setText("Calcular");
        btn_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_productoActionPerformed(evt);
            }
        });

        jLabel14.setText("Matriz Relacion");

        btn_relacionB.setText("B");
        btn_relacionB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_relacionBActionPerformed(evt);
            }
        });

        btn_relacionA.setText("A");
        btn_relacionA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_relacionAActionPerformed(evt);
            }
        });

        txt_numRelacion.setText(" ");

        lb_Mr.setText("Mr :");

        jLabel16.setText("n: ");

        btn_producto1.setText("Calcular");
        btn_producto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_producto1ActionPerformed(evt);
            }
        });

        btn_propiedades.setText("Propiedades");
        btn_propiedades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_propiedadesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_raunion))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_junta))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_producto)
                            .addComponent(jLabel14)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lb_Mr, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_numRelacion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(btn_relacionA)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_relacionB))
                                .addComponent(btn_producto, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btn_producto1))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btn_propiedades)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(btn_reiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(258, 258, 258))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(btn_junta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(btn_raunion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lb_producto)
                                    .addComponent(btn_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_relacionB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_relacionA, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_numRelacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)
                                    .addComponent(lb_Mr)
                                    .addComponent(btn_producto1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(btn_reiniciar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_propiedades, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pn_generalLayout = new javax.swing.GroupLayout(pn_general);
        pn_general.setLayout(pn_generalLayout);
        pn_generalLayout.setHorizontalGroup(
            pn_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_generalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pn_generalLayout.setVerticalGroup(
            pn_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_generalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_general, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_general, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_juntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_juntaActionPerformed
        // TODO add your handling code here:
        if (matriz == null) {
            JOptionPane.showMessageDialog(null, "llene los tres conjuntos por favor");
        } else {
            if ((matriz.getNum_col_A() == matriz.getNum_col_B() && matriz.getNum_fil_A() == matriz.getNum_fil_B())) {
                int r[][] = matriz.junta();
                dtmR = (DefaultTableModel) tb_resultante.getModel();
                dtmR.setColumnCount(r[0].length);
                dtmR.setRowCount(r.length);
                for (int i = 0; i < r.length; i++) {
                    for (int j = 0; j < r[0].length; j++) {
                        dtmR.setValueAt(r[i][j], i, j);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Para realizar la junta ambas matrices deben tener el mismo tamaño");
            }
        }
    }//GEN-LAST:event_btn_juntaActionPerformed

    private void btn_raunionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_raunionActionPerformed
        // TODO add your handling code here:
        if (matriz == null) {
            JOptionPane.showMessageDialog(null, "llene los tres conjuntos por favor");
        } else {
            if ((matriz.getNum_col_A() == matriz.getNum_col_B() && matriz.getNum_fil_A() == matriz.getNum_fil_B())) {
                int r[][] = matriz.reunion();
                dtmR = (DefaultTableModel) tb_resultante.getModel();
                dtmR.setColumnCount(r[0].length);
                dtmR.setRowCount(r.length);
                for (int i = 0; i < r.length; i++) {
                    for (int j = 0; j < r[0].length; j++) {
                        dtmR.setValueAt(r[i][j], i, j);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Para realizar la reunión ambas matrices deben tener el mismo tamaño");
            }
        }

    }//GEN-LAST:event_btn_raunionActionPerformed

    private void btn_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_productoActionPerformed
        // TODO add your handling code here:
        if (matriz == null) {
            JOptionPane.showMessageDialog(null, "llene los tres conjuntos por favor");
        } else {
            if (matriz.getNum_col_A() == matriz.getNum_fil_B()) {
                int r[][] = matriz.Producto(this.matriz.getA(), this.matriz.getB());
                dtmR = (DefaultTableModel) tb_resultante.getModel();
                dtmR.setColumnCount(r[0].length);
                dtmR.setRowCount(r.length);
                for (int i = 0; i < r.length; i++) {
                    for (int j = 0; j < r[0].length; j++) {
                        dtmR.setValueAt(r[i][j], i, j);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Para realizar el producto booleano el número de columnas de la matriz A debe ser igual al número de filas de la matriz B");
            }
        }
    }//GEN-LAST:event_btn_productoActionPerformed

    private void btn_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearActionPerformed
        // TODO add your handling code here:                     

        if (this.VALIDAR_TAMAÑO()) {
            dtmA = (DefaultTableModel) tb_A.getModel();
            dtmA.setColumnCount(Integer.parseInt(this.txt_col_A.getText()));
            dtmA.setRowCount(Integer.parseInt(this.txt_fil_A.getText()));
            dtmB = (DefaultTableModel) tb_B.getModel();
            dtmB.setColumnCount(Integer.parseInt(this.txt_col_B.getText()));
            dtmB.setRowCount(Integer.parseInt(this.txt_fil_B.getText()));
        } else {
            JOptionPane.showMessageDialog(null, "llene el tamaño de las matrices correctamente y con numeros mayores a 0");
        }
    }//GEN-LAST:event_btn_crearActionPerformed

    private void btn_llenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_llenarActionPerformed

        if (this.VALIDAR_TAMAÑO() == true) {
            if (this.VALIDAR_NUMEROS() == true) {
                int nfa = Integer.parseInt(this.txt_fil_A.getText());
                int nca = Integer.parseInt(this.txt_col_A.getText());
                int nfb = Integer.parseInt(this.txt_fil_B.getText());
                int ncb = Integer.parseInt(this.txt_col_B.getText());
                int mA[][] = new int[nfa][nca];
                int mB[][] = new int[nfb][ncb];
                for (int i = 0; i < nfa; i++) {
                    for (int j = 0; j < nca; j++) {
                        mA[i][j] = Integer.parseInt(dtmA.getValueAt(i, j) + "");
                    }
                }
                for (int i = 0; i < nfb; i++) {
                    for (int j = 0; j < ncb; j++) {
                        mB[i][j] = Integer.parseInt(dtmB.getValueAt(i, j) + "");
                    }
                }
                matriz = new Matriz_Booleana(mA, mB, nfa, nca, nfb, ncb);
            } else {
                JOptionPane.showMessageDialog(null, "los numeros de las matrices deben ser 1 o 0");
            }
        } else {
            JOptionPane.showMessageDialog(null, "llene el tamaño de las matrices correctamente y con numeros mayores a 0");
        }
    }//GEN-LAST:event_btn_llenarActionPerformed

    private void btn_reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reiniciarActionPerformed
        // TODO add your handling code here:
        this.aux_tb1 = new DefaultTableModel();
        this.aux_tb2 = new DefaultTableModel();
        this.aux_tb3 = new DefaultTableModel();
        this.aux_tb1.setColumnCount(3);
        this.aux_tb1.setRowCount(3);
        this.aux_tb2.setColumnCount(3);
        this.aux_tb2.setRowCount(3);
        this.aux_tb3.setColumnCount(3);
        this.aux_tb3.setRowCount(3);
        this.tb_A.setModel(aux_tb1);
        this.tb_B.setModel(aux_tb2);
        this.tb_resultante.setModel(aux_tb3);

        this.txt_col_A.setText("");
        this.txt_col_B.setText("");
        this.txt_fil_A.setText("");
        this.txt_fil_B.setText("");
        this.lb_Mr.setText("Mr :");
        matriz = null;
    }//GEN-LAST:event_btn_reiniciarActionPerformed

    private void btn_relacionBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_relacionBActionPerformed
        if (matriz == null) {
            JOptionPane.showMessageDialog(null, "Complete las matrices A y B correctamente");
        } else {
            this.lb_Mr.setText("Mr:  B");
        }
    }//GEN-LAST:event_btn_relacionBActionPerformed

    private void btn_relacionAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_relacionAActionPerformed
        if (matriz == null) {
            JOptionPane.showMessageDialog(null, "Complete las matrices A y B correctamente");
        } else {
            this.lb_Mr.setText("Mr:  A");
        }
    }//GEN-LAST:event_btn_relacionAActionPerformed

    private void btn_producto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_producto1ActionPerformed
        if (this.lb_Mr.getText().equals("Mr :") == true) {
            JOptionPane.showMessageDialog(null, "Seleccione la Matriz Relacion");
        } else {
            if (Integer.parseInt(this.txt_numRelacion.getText().replaceAll("\\s", "")) <= 0) {
                JOptionPane.showMessageDialog(null, "El número debe ser un entero y mayor a 0");
            } else {
                if (this.lb_Mr.getText().equals("Mr:  A") == true) {
                    int r[][] = matriz.Relaciones(matriz.A, Integer.parseInt(this.txt_numRelacion.getText().replaceAll("\\s", "")));
                    dtmR = (DefaultTableModel) tb_resultante.getModel();
                    dtmR.setColumnCount(r[0].length);
                    dtmR.setRowCount(r.length);
                    for (int i = 0; i < r.length; i++) {
                        for (int j = 0; j < r[0].length; j++) {
                            dtmR.setValueAt(r[i][j], i, j);
                        }
                    }
                } else {
                    int r[][] = matriz.Relaciones(matriz.B, Integer.parseInt(this.txt_numRelacion.getText().replaceAll("\\s", "")));
                    dtmR = (DefaultTableModel) tb_resultante.getModel();
                    dtmR.setColumnCount(r[0].length);
                    dtmR.setRowCount(r.length);
                    for (int i = 0; i < r.length; i++) {
                        for (int j = 0; j < r[0].length; j++) {
                            dtmR.setValueAt(r[i][j], i, j);
                        }
                    }
                }
            }

        }
    }//GEN-LAST:event_btn_producto1ActionPerformed

    private void btn_propiedadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_propiedadesActionPerformed
        // TODO add your handling code here:
        if (this.lb_Mr.getText().equals("Mr :") == true) {
            JOptionPane.showMessageDialog(null, "Seleccione la Matriz Relacion");
        } else {
            if (Integer.parseInt(this.txt_numRelacion.getText().replaceAll("\\s", "")) <= 0) {
                JOptionPane.showMessageDialog(null, "El número debe ser un entero y mayor a 0");
            } else {
                if (this.lb_Mr.getText().equals("Mr:  A") == true) {
                    int r[][] = matriz.Relaciones(matriz.A, Integer.parseInt(this.txt_numRelacion.getText().replaceAll("\\s", "")));
                    
                    
                    dtmR = (DefaultTableModel) tb_resultante.getModel();
                    dtmR.setColumnCount(r[0].length);
                    dtmR.setRowCount(r.length);
                    for (int i = 0; i < r.length; i++) {
                        for (int j = 0; j < r[0].length; j++) {
                            dtmR.setValueAt(r[i][j], i, j);
                        }
                    }
                } else {
                    int r[][] = matriz.Relaciones(matriz.B, Integer.parseInt(this.txt_numRelacion.getText().replaceAll("\\s", "")));
                    dtmR = (DefaultTableModel) tb_resultante.getModel();
                    dtmR.setColumnCount(r[0].length);
                    dtmR.setRowCount(r.length);
                    for (int i = 0; i < r.length; i++) {
                        for (int j = 0; j < r[0].length; j++) {
                            dtmR.setValueAt(r[i][j], i, j);
                        }
                    }
                }
            }

        }
    }//GEN-LAST:event_btn_propiedadesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    //Variables Create
    Matriz_Booleana matriz;
    DefaultTableModel dtmA, dtmB, dtmR, aux_tb1, aux_tb2, aux_tb3;

    public boolean VALIDAR_TAMAÑO() {
        int num_1;
        int num_2;
        int num_3;
        int num_4;
        try {
            num_1 = Integer.parseInt(this.txt_col_A.getText());
            num_2 = Integer.parseInt(this.txt_col_B.getText());
            num_3 = Integer.parseInt(this.txt_fil_A.getText());
            num_4 = Integer.parseInt(this.txt_fil_B.getText());
            if ((num_1 > 0) && (num_2 > 0) && (num_3 > 0) && (num_4 > 0)) {
                return true;
            } else {
                return false;
            }
        } catch (Exception e) {
            return false;
        }
    }

    public boolean VALIDAR_NUMEROS() {
        int num;
        boolean permitir = true;
        int nfa = Integer.parseInt(this.txt_fil_A.getText());
        int nca = Integer.parseInt(this.txt_col_A.getText());
        int nfb = Integer.parseInt(this.txt_fil_B.getText());
        int ncb = Integer.parseInt(this.txt_col_B.getText());

        try {
            for (int i = 0; i < nfa; i++) {
                for (int j = 0; j < nca; j++) {
                    num = Integer.parseInt(this.tb_A.getValueAt(i, j) + "");
                    if (num < 0 || num > 1) {
                        permitir = false;
                        break;
                    }
                }
            }
        } catch (Exception e) {
            permitir = false;
        }

        if (permitir == false) {
            return permitir;
        } else {
            try {
                for (int i = 0; i < nfb; i++) {
                    for (int j = 0; j < ncb; j++) {
                        num = Integer.parseInt(this.tb_B.getValueAt(i, j) + "");
                        if (num < 0 || num > 1) {
                            permitir = false;
                            break;
                        }
                    }
                }
            } catch (Exception e) {
                permitir = false;
            }
            return permitir;
        }

    }

    // Variables declaration modify

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_crear;
    private javax.swing.JButton btn_junta;
    private javax.swing.JButton btn_llenar;
    private javax.swing.JButton btn_producto;
    private javax.swing.JButton btn_producto1;
    private javax.swing.JButton btn_propiedades;
    private javax.swing.JButton btn_raunion;
    private javax.swing.JButton btn_reiniciar;
    private javax.swing.JButton btn_relacionA;
    private javax.swing.JButton btn_relacionB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lb_Mr;
    private javax.swing.JLabel lb_producto;
    private javax.swing.JPanel pn_general;
    private javax.swing.JTable tb_A;
    private javax.swing.JTable tb_B;
    private javax.swing.JTable tb_resultante;
    private javax.swing.JTextField txt_col_A;
    private javax.swing.JTextField txt_col_B;
    private javax.swing.JTextField txt_fil_A;
    private javax.swing.JTextField txt_fil_B;
    private javax.swing.JTextField txt_numRelacion;
    // End of variables declaration//GEN-END:variables
}
